const en = {
    'Hello': 'Hello',
    'Delivering': 'We are delivering happiness',
    'CurrentLocation': 'My Current Location',
    'PopularCategories': 'Popular Categories',
    'Vegetarian': 'Vegetarian',
    'PopularRestaurants': 'Popular Restaurants',
    'SeeAll': 'See All',
    'RecentOrders': 'Recent Orders',
    'RecentlyAdded': 'Recently Added',
    'InviteFriends': 'Invite friends and pay less',
    'FreeCredit': 'Invite friends and earn free credit with',
    'TheirFirstOrder': 'their first order',
    'FreeDelivery': 'Free Delivery',
    'Typesofrestaurants': 'Types of restaurants',
    'All': 'All',
    'PromoCode': 'Promo Code',
    'EnterPromoCode': 'Enter Promo Code',
    'Apply': 'Apply',
    'General': 'General',
    'MyAccount': 'My Account',
    'Address': 'Address',
    'Billing': 'Billing/Payment',
    'Settings': 'Settings',
    'Language': 'Language',
    'DarkMode': 'Dark Mode',
    'ChooseCategory': 'Choose Category',
    'Order': 'Order',
    'For': 'for',
    'Checkout': 'Checkout',
    'YourOrder': 'Your Order',
    'AddProduct': 'Add Product',
    'DeliveryAddress': 'Delivery Address',
    'PaymentMethod': 'Payment Method',
    'ConfirmOrder': 'Confirm Order',
    'Reorder': 'Reorder',
    'Date': '{{date}}',
    'Price': '${{price}}',
    'Profile': 'Profile',
    'MyAccount': 'My Account',
    'Address': 'Address',
    'Billing': 'Billing/Payment',
    'Asian': 'Asian',
    'Vegetarian': 'Vegetarian',
    'Mexican': 'Mexican',
    'Chicken': 'Chicken',
    'Fish': 'Fish',
    'Breakfast': 'Breakfast',
    'Salad': 'Salad',
    'IceCream': 'Ice Cream',
    'Beverages': 'Beverages',
    'Filter': 'Filter',
    'SortBy': 'Sort By',
    'Rating': 'Rating',
    'DeliveryTime': 'Delivery Time',
    'DeliveryPrice': 'Delivery Price',
    'Clear': 'Clear',
    'SearchRestaurants': 'Search Restaurants'

}

const fr = {
    'Hello': 'Bonjour',
    'Delivering': 'Nous vous livrons le bonheur',
    'CurrentLocation': 'Ma position actuelle',
    'PopularCategories': 'Catégories populaires',
    'Vegetarian': 'Végétarien',
    'PopularRestaurants': 'Restaurants populaires',
    'SeeAll': 'Voir tout',
    'RecentOrders': 'Commandes récentes',
    'RecentlyAdded': 'Récemment ajouté',
    'InviteFriends': 'Invitez des amis et payez moins',
    'FreeCredit': 'Invitez des amis et gagnez des crédits gratuits',
    'TheirFirstOrder': 'dès leur première commande',
    'FreeDelivery': 'Livraison gratuite',
    'Typesofrestaurants': 'Types de restaurants',
    'All': 'Tout',
    'PromoCode': 'Code promo',
    'EnterPromoCode': 'Entrez le code promo',
    'Apply': 'Appliquer',
    'General': 'Général',
    'MyAccount': 'Mon compte',
    'Address': 'Adresse',
    'Billing': 'Facturation / Paiement',
    'Settings': 'Paramètres',
    'Language': 'Langue',
    'DarkMode': 'Mode sombre',
    'ChooseCategory': 'Choisir une catégorie',
    'Order': 'Commandez',
    'For': 'pour',
    'Checkout': 'Check-out',
    'YourOrder': 'Votre commande',
    'AddProduct': 'Ajouter un produit',
    'DeliveryAddress': 'Adresse de livraison',
    'PaymentMethod': 'Mode de paiement',
    'ConfirmOrder': 'Confirmer la commande',
    'Reorder': 'Recommander',
    'Date': '{{date}}',
    'Price': '€{{price}}',
    'Profile': 'Profil',
    'MyAccount': 'Mon compte',
    'Address': 'Adresse',
    'Billing': 'Facturation / Paiement',
    'Asian': 'Asiatique',
    'Vegetarian': 'Vegétarien',
    'Mexican': 'Mexicain',
    'Chicken': 'Poulet',
    'Fish': 'Poisson',
    'Breakfast': 'Petit déjeuner',
    'Salad': 'Salade',
    'IceCream': 'Glace',
    'Beverages': 'Boissons',
    'Filter': 'Filtre',
    'SortBy': 'Trier par',
    'Rating': 'Évaluation',
    'DeliveryTime': 'Temps de livraison',
    'DeliveryPrice': 'Prix de livraison',
    'Clear': 'Réinitialiser',
    'SearchRestaurants': 'Recherche'
}

export { en, fr}